// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"
	"strconv"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"

	models "github.com/z7zmey/golang-microservice-boilerplate/internal/transport/rest/server/models"
)

// CarHandlerFunc turns a function with the right signature into a car handler
type CarHandlerFunc func(CarParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CarHandlerFunc) Handle(params CarParams) middleware.Responder {
	return fn(params)
}

// CarHandler interface for that can handle valid car params
type CarHandler interface {
	Handle(CarParams) middleware.Responder
}

// NewCar creates a new http.Handler for the car operation
func NewCar(ctx *middleware.Context, handler CarHandler) *Car {
	return &Car{Context: ctx, Handler: handler}
}

/*Car swagger:route GET /car car

return cars

car by id

*/
type Car struct {
	Context *middleware.Context
	Handler CarHandler
}

func (o *Car) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCarParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CarOKBody car o k body
// swagger:model CarOKBody
type CarOKBody struct {

	// data
	// Required: true
	Data []*models.Car `json:"data"`
}

// Validate validates this car o k body
func (o *CarOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *CarOKBody) validateData(formats strfmt.Registry) error {

	if err := validate.Required("carOK"+"."+"data", "body", o.Data); err != nil {
		return err
	}

	for i := 0; i < len(o.Data); i++ {
		if swag.IsZero(o.Data[i]) { // not required
			continue
		}

		if o.Data[i] != nil {
			if err := o.Data[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("carOK" + "." + "data" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *CarOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CarOKBody) UnmarshalBinary(b []byte) error {
	var res CarOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
