produces:
  - application/json
schemes:
  - http
swagger: "2.0"
info:
  title: boilerplate-microservice
  version: "1.0"
basePath: /
paths:
  /healthcheck:
    get:
      security: []
      summary: health check
      operationId: healthcheck
      responses:
        "200":
          description: OK
  /car:
    get:
      security: []
      description: car by id
      summary: return cars
      operationId: car
      parameters:
        - $ref: '#/parameters/id'
      responses:
        "200":
          description: OK
          schema:
            type: object
            required:
            - data
            properties:
              data:
                type: array
                items:
                  $ref: '#/definitions/car'
        "400":
          description: Bad Argument
          schema:
            $ref: '#/definitions/Error'
        "404":
          description: Not found
          schema:
            $ref: '#/definitions/Error'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/Error'

definitions:
  Error:
    type: object
    properties:
      code:
        description: status code
        type: integer
      message:
        type: string
  car:
    type: object
    required:
      - id
      - type
      - manufacturer
    properties:
      id:
        type: integer
      type:
        type: string
      manufacturer:
        type: string

parameters:
  id:
    type: integer
    description: car id
    name: id
    in: query
    required: true
